CREATE TABLE "my-invoices" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"project" "projects" NOT NULL,
	"mode_of_project" "mode_of_projects" NOT NULL,
	"state" "states" NOT NULL,
	"my_bill_category" "my_bill_categorys" NOT NULL,
	"milestone" "milestonees",
	"invoice_number" varchar(255) NOT NULL,
	"invoice_date" date NOT NULL,
	"submission_date" date NOT NULL,
	"invoice_basic_amount" numeric NOT NULL,
	"gst_percentage" "gst_percentages" NOT NULL,
	"invoice_gst_amount" numeric DEFAULT '0' NOT NULL,
	"total_amount" numeric DEFAULT '0' NOT NULL,
	"passed_amount_by_client" numeric DEFAULT '0',
	"retention" numeric DEFAULT '0' NOT NULL,
	"gst_withheld" numeric DEFAULT '0' NOT NULL,
	"tds" numeric DEFAULT '0' NOT NULL,
	"gst_tds" numeric DEFAULT '0' NOT NULL,
	"bocw" numeric DEFAULT '0' NOT NULL,
	"low_depth_deduction" numeric DEFAULT '0' NOT NULL,
	"ld" numeric DEFAULT '0' NOT NULL,
	"sla_penalty" numeric DEFAULT '0' NOT NULL,
	"penalty" numeric DEFAULT '0' NOT NULL,
	"other_deduction" numeric DEFAULT '0' NOT NULL,
	"total_deduction" numeric DEFAULT '0' NOT NULL,
	"net_payable" numeric DEFAULT '0' NOT NULL,
	"status" "pay-status" NOT NULL,
	"amount_paid_by_client" numeric DEFAULT '0' NOT NULL,
	"payment_date" date,
	"balance" numeric DEFAULT '0' NOT NULL,
	"remarks" text
);
--> statement-breakpoint
DROP TABLE "invoices" CASCADE;